name: dashbord_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  number_paginator: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  dropdown_button2: ^2.3.9
  table_calendar: ^3.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  #fonts:
  #  - family: NT
  #    fonts:
  #     - asset: assets/fonts/NT_regular.ttf
  #     - asset: assets/fonts/NT_Bold.ttf
  #        weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
